#!/bin/bash
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2SUP").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CSOC").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2AN").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2MOIS").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2JOUR").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2NSEQ").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2NDOS").fields[].field_size) = 3' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CANA").fields[].field_size) = 5' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2LANA").fields[].field_size) = 3' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2RANG").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2REAL").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2PAIF").fields[].field_size) = 3' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2PAIC").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CX1").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CX2").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CX3").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CX4").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2TAUX").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CODB").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2NBB").fields[].field_size) = 4' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CSSB").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2GRP").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2SGRP").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2RESU").fields[].field_size) = 70' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ZON1").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ZON2").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ZON3").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ZON4").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2EGRP").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ZON5").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ZON6").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CONN").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2PAIE").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2RETE").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2HN").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CALC").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2OBLI").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2DDOS").fields[].field_size) = 8' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2HPRD").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2HPRR").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2FXCO").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2FXM1").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2FXM2").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2SAIS").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CRED").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2VALI").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2MEDE").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CSS").fields[].field_size) = 5' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CFAC").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2MFAC").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2STAT").fields[].field_size) = 5' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CRES").fields[].field_size) = 6' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2SUGR").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2TOTI").fields[].field_size) = 3' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CANT").fields[].field_size) = 8' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2NCLI").fields[].field_size) = 9' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CHRP").fields[].field_size) = 3' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2DATP").fields[].field_size) = 8' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CSOR").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2REAR").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CEXO").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2SAIA").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2RGLA").fields[].field_size) = 5' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2PGRP").fields[].field_size) = 5' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ACCR").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2VALR").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CPHR").fields[].field_size) = 8' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ATM1").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ATM2").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ATCO").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ATC1").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ATC2").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ATC3").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ATC4").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ATC5").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2CPTA").fields[].field_size) = 10' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2PRHT").fields[].field_size) = 2' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2EXEC").fields[].field_size) = 10' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2LOIN").fields[].field_size) = 15' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2PXE").fields[].field_size) = 11' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2PART").fields[].field_size) = 1' model.json | sponge model.json
jq '(.[] | select(.table_name == "TRA2PF") | select(.fields[].field_name == "T2ANAA").fields[].field_size) = 8' model.json | sponge model.json
